### ISSUE TITLE
Program only writes first 9 *.rvdata2 files

### ISSUE THREAD

**Issue by CluelessGuyNo11** [RPG-Maker-Translator/RPG-Maker-Translator#8]
Tried to run this a few times (after setting up the api) and at the end it starts listing rvdata2 files before moving the existing rgss3a file to backup, and indicating the number of lines and elapsed time. The translation is clearly being done, and creates json files, but for whatever reason it doesn't finish writing them back to rvdata2. The --dump argument mentioned in the readme doesn't seem to be recognized by the VXAce translator either, and running it by GUI or command prompt doesn't seem to make any difference.

**Comment by CluelessGuyNo11** [comment]
So the --dump argument mostly worked once I found it was --dump="dir", but one of the files displayed the .json (which was long enough I couldn't scroll to check the error) followed by the lines below.  

<pre>
from C:/Ruby24/lib/ruby/2.4.0/json/common.rb:156:in `parse'
from C:/Ruby24/lib/ruby/2.4.0/json/common.rb:335:in `load'
from C:/Users/me/Downloads/RPGMT/3rdparty/rmxp_translator/base_translator.rb:157:in `translate_file'
from C:/Users/me/Downloads/RPGMT/3rdparty/rmxp_translator/base_translator.rb:83:in `block in translate_files'
from C:/Users/me/Downloads/RPGMT/3rdparty/rmxp_translator/base_translator.rb:83:in `each'
from C:/Users/me/Downloads/RPGMT/3rdparty/rmxp_translator/base_translator.rb:83:in `translate_files'
from C:/Users/me/Downloads/RPGMT/3rdparty/rmxp_translator/base_translator.rb:74:in `block in do_commands'
from C:/Users/me/Downloads/RPGMT/3rdparty/rmxp_translator/base_translator.rb:74:in `each'
from C:/Users/me/Downloads/RPGMT/3rdparty/rmxp_translator/base_translator.rb:74:in `do_commands'
from rmvxace_translator.rb:6:in `main'
</pre>

Deleting the file (map003.rvdata2) and its .json allowed the program to apply the translations to all other files.

**Comment by CluelessGuyNo11** [comment]
After looking through the file, I eventually found a stray quotation mark that looked to have been in some of the translated text. Removing it solved the problem.

**Comment by vicktorhu** [comment]
Yeah I just solved my similar error. I know you have closed the issue, but I have some quick way to resolve it.

1. Check what *.rvdata files are missing from your Data folder
2. Find the bad *.JSON file on your DataExtracted folder. The program generate the rvdata files in iteration, so it shouldn't be too hard to guess.
3. Copy paste the content of our bad JSON file to https://jsonlint.com/ to easily find the error.
4. Recompile your scripts. I use this command for VX Ace games `ruby "[PATH TO RPGM TRANSLATOR]/RPG-Maker-Translator-master/3rdParty/rmxp_translator/rmvxace_translator.rb" --translate="[PATH TO GAME]/DataExtracted/*.rvdata2" --dest="[PATH TO GAME]/Data"`
5. Repeat to first step if you get any error, until you have all the *.rvdata files on DataExtracted inside the Data folder.

So far worked great, though I can't fix a bad 'script.rvdata' file yet. I just copy pasted the untranslated 'script.rvdata' from DataExtracted folder.
